version: "3"
services:
  neo4j:
    image: neo4j:5.18
    container_name: bio-kg-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: "neo4j/surplus0710"
      NEO4J_server_memory_heap_initial__size: 1G
      NEO4J_server_memory_heap_max__size: 2G
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt
    volumes:
      - ./neo4j_data:/data   # 로컬 퍼시스턴스